[env:wemos_d1_mini32]
platform = espressif32@6.5.0
board = wemos_d1_mini32
framework = arduino
lib_deps =
    https://github.com/pschatzmann/ESP32-A2DP.git
    https://github.com/pschatzmann/arduino-audio-tools.git
monitor_speed = 115200
build_flags =
    -DCONFIG_BT_ENABLED
    -DCONFIG_BT_CLASSIC_ENABLED
board_build.partitions = huge_app.csv