[env:wemos_d1_mini32]
platform = espressif32@7.0.1
board = wemos_d1_mini32
framework = arduino
extra_scripts =
    pre:gen_bintobar.py
    ; pre:gen_font.py
lib_deps =
    https://github.com/pschatzmann/ESP32-A2DP.git
    https://github.com/pschatzmann/arduino-audio-tools.git
    https://github.com/pschatzmann/arduino-libhelix.git
    olikraus/u8g2
    kosme/arduinoFFT
monitor_speed = 115200
build_flags =
    ; -DCORE_DEBUG_LEVEL=3 
    -DCONFIG_ARDUINO_LOOP_STACK_SIZE=4096
    ; -DCONFIG_BTDM_CTRL_MODE_BR_EDR_ONLY=y
    -DCONFIG_BT_BLE_ENABLED=n
board_build.partitions = huge_app.csv
board_build.filesystem = littlefs